#!/usr/bin/env node
import { execFileSync } from "node:child_process"
import { writeFileSync } from "node:fs"
import { resolve } from "node:path"

/**
 * Writes `.env.e2e` from the running local Supabase stack.
 *
 * The CLI mints fresh keys per project, so hard-coding them in a committed file
 * guarantees a confusing "Invalid API key" the first time someone's stack
 * differs. Reading them back from `supabase status` keeps the two in step.
 *
 * MinIO stands in for Cloudflare R2. The app talks to R2 over the S3 API with
 * `forcePathStyle`, so the only things that change are the endpoint and the
 * credentials.
 */

const OUTPUT_PATH = resolve(process.cwd(), ".env.e2e")

const MINIO = {
  accessKey: "bizflow-e2e",
  bucket: "bizflow-e2e",
  endpoint: "http://127.0.0.1:9000",
  secretKey: "bizflow-e2e-secret",
}

/**
 * Reads the local stack's connection details.
 *
 * @returns Parsed `supabase status` output.
 */
function readSupabaseStatus() {
  let raw

  try {
    raw = execFileSync(
      "corepack",
      ["pnpm", "exec", "supabase", "status", "-o", "json"],
      { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }
    )
  } catch (error) {
    throw new Error(
      "Could not read `supabase status`. Start the local stack first with " +
        "`pnpm e2e:up`.",
      { cause: error }
    )
  }

  // The CLI prints human-readable warnings before the JSON body on some
  // versions, so parse from the first brace rather than trusting the whole
  // stream to be JSON.
  const start = raw.indexOf("{")

  if (start === -1) {
    throw new Error("`supabase status` returned no JSON object.")
  }

  return JSON.parse(raw.slice(start))
}

const status = readSupabaseStatus()

const apiUrl = status.API_URL
const anonKey = status.ANON_KEY
const serviceRoleKey = status.SERVICE_ROLE_KEY

for (const [name, value] of Object.entries({
  ANON_KEY: anonKey,
  API_URL: apiUrl,
  SERVICE_ROLE_KEY: serviceRoleKey,
})) {
  if (typeof value !== "string" || value.length === 0) {
    throw new Error(`\`supabase status\` did not report ${name}.`)
  }
}

const lines = [
  "# Generated by scripts/write-e2e-env.mjs — do not edit or commit.",
  "# Regenerate with `pnpm e2e:env` after restarting the local stack.",
  "",
  "NODE_ENV=production",
  "NEXT_PUBLIC_APP_ENV=test",
  'NEXT_PUBLIC_APP_NAME="BizFlow Docs"',
  "NEXT_PUBLIC_APP_URL=http://localhost:3000",
  "APP_URL=http://localhost:3000",
  "AUTH_REDIRECT_URL=http://localhost:3000/auth/callback",
  "PUBLIC_FORM_BASE_URL=http://localhost:3000/forms",
  "",
  `SUPABASE_URL=${apiUrl}`,
  `SUPABASE_PUBLISHABLE_KEY=${anonKey}`,
  `SUPABASE_SECRET_KEY=${serviceRoleKey}`,
  "",
  "# MinIO speaks the S3 API that the R2 client already targets.",
  "CLOUDFLARE_R2_ACCOUNT_ID=e2e",
  `CLOUDFLARE_R2_ACCESS_KEY_ID=${MINIO.accessKey}`,
  `CLOUDFLARE_R2_SECRET_ACCESS_KEY=${MINIO.secretKey}`,
  `CLOUDFLARE_R2_BUCKET_NAME=${MINIO.bucket}`,
  `CLOUDFLARE_R2_ENDPOINT=${MINIO.endpoint}`,
  "CLOUDFLARE_R2_REGION=auto",
  "CLOUDFLARE_R2_SIGNED_URL_TTL_SECONDS=900",
  "",
  "# Deterministic runs: no outbound email, SMS, AI, or analytics.",
  "SMS_PROVIDER=disabled",
  "ANALYTICS_PROVIDER=disabled",
  "NEXT_PUBLIC_ANALYTICS_PROVIDER=disabled",
  "AI_PROVIDER=gemini",
  "AI_MODEL=gemini-3.6-flash",
  "AI_TIMEOUT_MS=30000",
  "",
  "# Rate limiting is disabled when Upstash is unset, which is what a suite",
  "# that signs in repeatedly from one address needs.",
  "UPSTASH_REDIS_REST_URL=",
  "UPSTASH_REDIS_REST_TOKEN=",
  "",
  "CRON_SECRET=e2e-cron-secret-value",
  "FILE_UPLOAD_MAX_BYTES=20971520",
  "NEXT_PUBLIC_FILE_UPLOAD_MAX_BYTES=20971520",
  "FILE_UPLOAD_MAX_FILES_PER_SUBMISSION=10",
  "FILE_UPLOAD_SIGNED_URL_TTL_SECONDS=900",
  "FILE_UPLOAD_ALLOWED_MIME_TYPES=application/pdf,image/png,image/jpeg,text/csv",
  "NEXT_PUBLIC_FILE_UPLOAD_ALLOWED_MIME_TYPES=application/pdf,image/png,image/jpeg,text/csv",
  "",
  "FEATURE_PUBLIC_FORMS=true",
  "NEXT_PUBLIC_FEATURE_PUBLIC_FORMS=true",
  "FEATURE_SMS_NOTIFICATIONS=false",
  "NEXT_PUBLIC_FEATURE_SMS_NOTIFICATIONS=false",
  "FEATURE_OFFLINE_DRAFTS=false",
  "NEXT_PUBLIC_FEATURE_OFFLINE_DRAFTS=false",
  "FEATURE_ANALYTICS=false",
  "NEXT_PUBLIC_FEATURE_ANALYTICS=false",
  "",
]

writeFileSync(OUTPUT_PATH, `${lines.join("\n")}\n`, "utf8")

console.info("e2e_env_written", {
  outputPath: OUTPUT_PATH,
  supabaseApiUrl: apiUrl,
})
